# Generated by Django 3.1.1 on 2020-10-05 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_orderproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderProduct',
        ),
    ]
