# Generated by Django 3.1.1 on 2020-10-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_sub_cat_main_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='photo_5',
            new_name='photo_3',
        ),
        migrations.AddField(
            model_name='product',
            name='photo_4',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
